Upgrading Build Workflow to publish Docker Images on Release
nabla-c0d3/sslyze pull request #527
Opened 2021-09-27 17:00 UTC by rseedorff

This PR if applied closes #521 by upgrading the sslyze repository GitHub Actions and Workflows.
* Merged all pre existing test related workflows into a single one `run_tests.yaml`
* Updated the Docker Image to the newest Python image `3.9-slim`
* Added a new release pipeline which will be triggered with every new GitHub release to publish the corresponding Docker Image to DockerHub. To get this work you have to add 3 new repository secrets with the namespace and a docker user with `red & write` permission for the docker repository:
  * DOCKER_NAMESPACE: `nablac0d3`
  * DOCKER_USERNAME: `nablac0d3`
  * DOCKER_TOKEN: _YOUR_USER_PASSWORD_
  
  I tested the release pipeline already within our fork successfully (with our project docker repo instead): https://github.com/secureCodeBox/sslyze/runs/3722635578?check_suite_focus=true

2021-09-28 05:02 UTC, nabla-c0d3 commented
Hey this is great! One request tho - can you revert to separate workflows (scan_nginx_server.yml, etc.). They were separate by design. Once you've done that I will take a look again but overall it looks good! Thanks,

2021-09-28 15:46 UTC, nabla-c0d3 requested changes
I asked for a couple more small changes and then this should be good to go. Thanks!

2021-09-28 15:46 UTC, nabla-c0d3 commented on .github/workflows/release-build.yaml
> +name: "Release Build"
Can you rename this file to release-to-docker.yml ?

2021-09-28 15:46 UTC, nabla-c0d3 commented on .github/workflows/release-build.yaml
> +name: "Release Build"
and "Release to Docker"

2021-09-28 15:46 UTC, nabla-c0d3 commented on .github/workflows/scan_apache2_server.yml
> +        python-version: [3.7, 3.8, 3.9]
Let's not use a test matrix for the scan_xxx_server Actions (it's "too much testing"). Can you revert to Python 3.8 ?

2021-10-01 08:24 UTC, rseedorff commented
@nabla-c0d3 ready when you are 🙂

2021-10-02 20:20 UTC, merged

2021-10-02 20:20 UTC, nabla-c0d3 commented
Thank you!

2021-10-02 20:47 UTC, nabla-c0d3 commented
@rseedorff I tried to trigger the workflow just now by creating the "test-docker-release-1" git tag, but nothing happened. The workflow was not triggered. What am I doing wrong? Thanks!

2021-10-03 19:19 UTC, rseedorff commented
@nabla-c0d3 First of all it is necessary to define the repo secrets mentioned in my PR description. 
Secondly the workflow will be started only by creating a new GitHub release here: https://github.com/nabla-c0d3/sslyze/releases Just tagging is not enough 😕 

Hint 1:
If you want to test the workflow before publishing a new sslyze release you can temporary add a `on push` for example into the workflow :
```yaml
on:
  push:
  release:
    types: [released]

```

Hint 2:
If it is important to you to trigger this workflow only by pushing a tag it must be defined like the following example (not tested yet):

```yaml 
# Only release on a new tag that is a version number.
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
```

I found this solution here:
* https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
* https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/26
* https://github.com/actions/runner/issues/1007

2021-10-06 03:59 UTC, nabla-c0d3 commented
@rseedorff Thanks!

I just tried and it looks like it worked 😀: https://hub.docker.com/r/nablac0d3/sslyze/tags?page=1&ordering=last_updated (from https://github.com/nabla-c0d3/sslyze/releases/tag/test-docker-release-1).

One thing tho: the tag in Dockerhub should have the same name as the tag (or release name) in GitHub. Hence in Dockerhub, the above tag should have been called test-docker-release-1, but instead it is called "sha-7e16dc0".

Any ideas on how to send the proper tag name to Dockerhub? It can also be the release name (in SSLyze tag name and release name are the same).

2021-10-08 09:58 UTC, rfelber commented
Hi @nabla-c0d3,

great news 🎉   
The sha tag is introduced due to the following definition in the workflow Action (https://github.com/docker/metadata-action#typesha). You can drop this tag option, its optional:
```
        with:
          images: ${{ env.DOCKER_NAMESPACE }}/sslyze
          tags: |
            type=sha 
```
The second tag definition is based on the semver string format (https://github.com/docker/metadata-action#typesemver) and uses your release tag for that ({{version}}):
```
with:
          images: ${{ env.DOCKER_NAMESPACE }}/sslyze
          tags: |
            type=sha
            type=semver,pattern={{version}}
```
Since your tag name `test-docker-release-1)` is not compliant to the sermver format i would guess its dropped. It should work with an valid release tag like `v4.2.0-rc.1`

2021-10-16 22:13 UTC, nabla-c0d3 commented
Hi @rseedorff ,

Thank you and sounds good. I will then try it with the next release, which will be properly formatted (it will be 5.0.0). It looks like we are good to go 👍